Numpy is used due to it's usage of c/c++ processing, making its data structures much faster than native Python data structures.

In [1]:
import numpy as np

In [2]:
a = np.array((2, 3, 4, 6))

In [ ]:
b = np.array(
    [
        [1, 2, 3], [4, 5, 6]
    ]
)

In [4]:
c = np.array([
    [
        [1, 2, 3], [4, 5, 6]
    ],
    [
        [7, 8, 9], [10, 11, 12]
    ]
])

In [6]:
for x in c:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [7]:
for x in np.nditer(c):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [9]:
for idx, x in np.ndenumerate(c):
    print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [13]:
c[0, 1]

array([4, 5, 6])

In [14]:
np.exp(b)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [15]:
d = {
    'name': ['jay', 'jared'],
    'birth': [1997]
}

In [17]:
d.values()

dict_values([['jay', 'jared'], [1997]])

In [18]:
d.items()

dict_items([('name', ['jay', 'jared']), ('birth', [1997])])

In [19]:
list(d.items())

[('name', ['jay', 'jared']), ('birth', [1997])]

In [20]:
for x in d:
    print(x)

name
birth


In [21]:
for x, y in d.items():
    print(x, y)

name ['jay', 'jared']
birth [1997]


In [ ]:
sorted(d.items())  # Sorts by key

[('birth', [1997]), ('name', ['jay', 'jared'])]

In [26]:
e = {'pear': 1.99, 'banana': 0.59, 'blueberry': 3.49}

In [ ]:
# Sort by price but keep original contents of dictionary
sorted([(price, name) for name, price in e.items()])

[(0.59, 'banana'), (1.99, 'pear'), (3.49, 'blueberry')]

In [ ]:
sorted(e.items(), key=lambda fruit: fruit[1])  # Alternative

[('banana', 0.59), ('pear', 1.99), ('blueberry', 3.49)]

In [28]:
e['pear']

1.99

In [29]:
e['apple']

KeyError: 'apple'

In [ ]:
e.get('apple')  # Gets object if it exists; gracefully handles KeyError

In [34]:
import pandas as pd

In [37]:
pd.DataFrame(b[0])

0
0  1
1  2
2  3