Numpy is used due to it's usage of c/c++ processing, making its data structures much faster than native Python data structures.

In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.array((2, 3, 4, 6))

In [4]:
b = np.array(
    [
        [1, 2, 3], [4, 5, 6]
    ]
)

In [5]:
c = np.array([
    [
        [1, 2, 3], [4, 5, 6]
    ],
    [
        [7, 8, 9], [10, 11, 12]
    ]
])

In [6]:
for x in c:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [7]:
for x in np.nditer(c):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [8]:
for idx, x in np.ndenumerate(c):
    print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [9]:
c[0, 1]

array([4, 5, 6])

In [10]:
np.exp(b)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [11]:
d = {
    'name': ['jay', 'jared'],
    'birth': [1997]
}

In [12]:
d.values()

dict_values([['jay', 'jared'], [1997]])

In [13]:
d.items()

dict_items([('name', ['jay', 'jared']), ('birth', [1997])])

In [14]:
list(d.items())

[('name', ['jay', 'jared']), ('birth', [1997])]

In [15]:
for x in d:
    print(x)

name
birth


In [16]:
for x, y in d.items():
    print(x, y)

name ['jay', 'jared']
birth [1997]


In [17]:
sorted(d.items())  # Sorts by key

[('birth', [1997]), ('name', ['jay', 'jared'])]

In [18]:
e = {'pear': 1.99, 'banana': 0.59, 'blueberry': 3.49}

In [19]:
# Sort by price but keep original contents of dictionary
sorted([(price, name) for name, price in e.items()])

[(0.59, 'banana'), (1.99, 'pear'), (3.49, 'blueberry')]

In [20]:
sorted(e.items(), key=lambda fruit: fruit[1])  # Alternative

[('banana', 0.59), ('pear', 1.99), ('blueberry', 3.49)]

In [21]:
e['pear']

1.99

In [22]:
e['apple']

KeyError: 'apple'

In [ ]:
e.get('apple')  # Gets object if it exists; gracefully handles KeyError

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(b[0])

0
0  1
1  2
2  3

In [31]:
a = pd.DataFrame(np.array(range(9)).reshape(3,3))
a

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [32]:
b = pd.DataFrame(np.array(range(10, 19)).reshape(3,3))
b

0   1   2
0  10  11  12
1  13  14  15
2  16  17  18

In [36]:
a.columns = ['a1', 'a2', 'a3']
b.columns = ['b1', 'b2', 'b3']

a, b

(   a1  a2  a3
 0   0   1   2
 1   3   4   5
 2   6   7   8,
    b1  b2  b3
 0  10  11  12
 1  13  14  15
 2  16  17  18)

In [38]:
a['a4'] = [1, 2, 4]
b['b4'] = [1, 2, 6]

In [39]:
a, b

(   a1  a2  a3  a4
 0   0   1   2   1
 1   3   4   5   2
 2   6   7   8   4,
    b1  b2  b3  b4
 0  10  11  12   1
 1  13  14  15   2
 2  16  17  18   6)

In [40]:
a.merge(b, how='inner', left_on='a4', right_on='b4')

a1  a2  a3  a4  b1  b2  b3  b4
0   0   1   2   1  10  11  12   1
1   3   4   5   2  13  14  15   2

In [41]:
a.melt(id_vars=['a4'], value_vars=['a1', 'a2', 'a3'], var_name='time', value_name='measurement')

a4 time  measurement
0   1   a1            0
1   2   a1            3
2   4   a1            6
3   1   a2            1
4   2   a2            4
5   4   a2            7
6   1   a3            2
7   2   a3            5
8   4   a3            8

In [43]:
c = pd.DataFrame({
    'c1': [1,2,3],
    'c2': [4,5,6]
})
c

c1  c2
0   1   4
1   2   5
2   3   6

In [44]:
pd.Series({
    'c1': [1,2,3]
})

c1    [1, 2, 3]
dtype: object

In [45]:
np.exp(c)

c1          c2
0   2.718282   54.598150
1   7.389056  148.413159
2  20.085537  403.428793

In [46]:
f = "abcsd"
f.startswith("ab"), f.endswith("s")

(True, False)

In [53]:
sample_output = ''
with open("sample.txt", 'r') as reader:
    sample_output = reader.readlines()
    sample_output = [
        text.strip('\n') for text in sample_output
    ]

print(sample_output[0].split('\n'))


['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.']
